[package]
name = "redeye"
version = "0.1.0"
authors = ["Nick Pillitteri <nick@tshlabs.org>"]

[dependencies]
tokio = "0.1"
futures = "0.1"
failure = "0.1"
failure_derive = "0.1"

[lib]
name = "redeye"
path = "src/redeye/lib.rs"
